### ISSUE TITLE
Capability to add directory to find method

### ISSUE THREAD

**Issue by Hajime-Suzuki** [Everduin94/nvim-quick-switcher#4]
Hello, thank you for developing such a nice plugin!

I frequently switch test and implementation files in Typescript. 

For example, when I have `a.ts` open, then `find` works well as expected
```
src/
└── domain/
    ├── a.ts
    └── __tests__/
        └── a.test.ts
```

However, I have several projects that have this structure. `find` doesn't work because the `tests` folder is more than 1 directory up.
```
src/
└── domain/
    └── a.ts
tests/
└── domain/
    └── a.test.ts
```

I wonder if you have a plan to support this structure. Maybe it would be nice to do something like `find('.+.test.ts | .+.ts', { regex = true, include = { 'tests' } })`

**Comment by Everduin94** [comment]
Thanks for trying it out, I appreciate it!

I've had this sort of thing on my radar for a while. I have a few ideas to try out for implementing it. --When I get the chance I'll look into this.

**Comment by Everduin94** [comment]
@Hajime-Suzuki -- Sorry for the really long delay. I'm working on some side-projects right now that are taking up a ton of time.

The solution I made might not be what you'd expect but you should be able to use it to accomplish what you mentioned.

I tried it out using the file structure you mentioned and it seemed to work for me.

Here is the PR: I would refer to the example because it is a little bit of a mess right now and I haven't gotten to test it very much or write any documentation: https://github.com/Everduin94/nvim-quick-switcher/pull/5

The gist is that you can pass a lua function to a new method `v2_find`. That lua function will get a bunch of information about the file / path which you can use to build the path/file/wildcard you're looking for.

So in the example you can see I do a simple version of replacing `src` with `test` and vice versa. This allows users to navigate back and forth or handle complex file structures.

Let me know if you need any help getting it setup! You'll need to target this branch: `poc-lua-fn-find`

**Comment by Everduin94** [comment]
I should add, it's very likely you want to use 1 keybind to jump to tests and this would sort of break that. -- I believe you can use an autocmd and remap keybinds based on project, so you could hypothetically set it up to always use the same binds but use a different function based on project. -- Probably not ideal so I'll see if I can figure out someway to handle this better.

**Comment by Hajime-Suzuki** [comment]
Thank you @Everduin94! 
I used your examples in the PR and it worked as expected for my use case 👍 Much appreciated. 
About the key binding, I'm good with having a different keymap because projects of mine/work don't have different folder structures. However, it'd be perfect to use a single key especially if you have multiple projects with different structures (e.g. `tests` folder has subfolders like `unit` and `integration`).

**Comment by Everduin94** [comment]
@Hajime-Suzuki - I think the user has the ability to do this with a little bit of effort. This is one of the reasons I liked the idea of passing in a function because the user gets access to using Lua & the Vim Utils to accomplish any type of behavior.

So for example, you could change the function you pass in to something like this:

```lua
local ex_find_test_fn = function (p)
  local path = p.path;
  local test_dir = path:gsub('src', 'test')
  local unit_dir = path:gsub('src', 'unit')
  local integration_dir = path:gsub('src', 'integration')
  local file_name = p.prefix;
  if vim.fn.isdirectory(test_dir) == 1 then
    return test_dir .. '/' .. file_name .. '*'
  elseif vim.fn.isdirectory(unit_dir) == 1 then
    return unit_dir .. '/' .. file_name .. '*'
  elseif vim.fn.isdirectory(integration_dir) == 1 then
    return integration_dir .. '/' .. file_name .. '*'
  end
end
```

^^ Although you'd only have to write it once, this is pretty involved for a plugin that I want to be very minimal setup hahah. -- My plan is to eventually create a list of `built_ins` or `utils` that handle common scenarios like this. -- Also thank you for the feedback and examples I appreciate it!

If this is working for you I'll write up some documentation, merge, and close this issue.
- I'm considering changing the name of the function, maybe `find_fn`?
